<?php

// This file is generated by Composer
require_once 'vendor/autoload.php';

$client = new \Github\Client();

$token = "XXXXXcreateYourOwnXXXXX";
$owner = 'mickaelandrieu';
$repository = 'test-modobot';
$issueId = 25;
$comment = 'Hello dear contributor, how are you?';

$client->authenticate($token, Client::AUTH_HTTP_TOKEN);
$client
    ->api('issue')
    ->comments()
    ->create(
        $owner,
        $repository,
        $issueId,
        ['body' => $comment]
    )
;