<?php
// This file is generated by Composer
require_once 'vendor/autoload.php';

$client = new \Github\Client();
$followers = $client->api('user')->following('mickaelandrieu');

foreach ($followers as $follower) {
    echo $follower['login'].PHP_EOL;
}

// see results in followers.txt file